# Generated by Django 3.0.3 on 2020-03-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200328_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='aboutus',
        ),
    ]
