# Generated by Django 3.0.3 on 2020-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_setting_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
    ]
