# Generated by Django 3.0.3 on 2020-05-04 15:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200328_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
