# Generated by Django 3.0.3 on 2020-05-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20200507_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
