# Generated by Django 3.0.3 on 2020-05-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
