# Generated by Django 3.0.3 on 2020-05-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_auto_20200510_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Food',
            new_name='food',
        ),
    ]
