# Generated by Django 3.0.3 on 2020-05-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_auto_20200510_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='food',
            new_name='Food',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='food',
            new_name='Food',
        ),
    ]
