# Generated by Django 3.0.3 on 2020-05-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
