# Generated by Django 3.0.3 on 2020-05-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_remove_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.Restaurant'),
            preserve_default=False,
        ),
    ]
